# <center> Exploratory Data Analysis </center>

## 1. Знакомство с библиотекой numpy

**NumPy** — библиотека языка Python, позволяющая [удобно] работать с многомерными массивами и матрицами, содержащая математические функции. Кроме того, NumPy позволяет векторизовать многие вычисления, имеющие место в машинном обучении. 

 - [numpy](http://www.numpy.org)
 - [numpy tutorial](http://cs231n.github.io/python-numpy-tutorial/)
 - [100 numpy exercises](http://www.labri.fr/perso/nrougier/teaching/numpy.100/)
 - [numpy data types](https://docs.scipy.org/doc/numpy/user/basics.types.html)

In [1]:
import numpy as np

Основным типом данных NumPy является многомерный массив элементов одного типа — [numpy.ndarray](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.array.html). Каждый подобный массив имеет несколько *измерений* или *осей* — в частности, вектор (в классическом понимании) является одномерным массивом и имеет 1 ось, матрица является двумерным массивом и имеет 2 оси и т.д.

Создать массив из списков или кортежей можно с помощью функции ```np.array()```. 

```np.array``` - функция, создающая объект типа ```np.ndarray```.

In [2]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
type(matrix)

numpy.ndarray

In [4]:
matrix.ndim

2

Чтобы узнать длину массива по каждой из осей, можно воспользоваться атрибутом ```shape```. Общее количество элементов выводим с помощью ```size```.

In [5]:
matrix.shape, matrix.size

((2, 3), 6)

Альтернативные способы задать матрицу:

In [6]:
np.matrix('1 2; 3 4') # аргумент - строка или список

matrix([[1, 2],
        [3, 4]])

In [7]:
np.ndarray(shape=(3,3), dtype='float') # из случайных чисел

array([[0.00000000e+000, 0.00000000e+000, 3.95252517e-323],
       [0.00000000e+000, 0.00000000e+000, 4.17201348e-309],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

Массивы специального вида можно создать при помощи функций zeros, ones, empty, identity:

In [8]:
np.zeros((3,))

array([0., 0., 0.])

In [9]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.empty((2, 5))

array([[ 0.00000000e+000, -1.72723382e-077,  2.47032823e-323,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -1.28822983e-231,
         9.88131292e-324,  6.95335581e-309]])

Еще можно создавать массивы при помощи функции arange:

In [12]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [13]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Вместо значения длины массива по одному из измерений можно указать -1 — в этом случае значение будет рассчитано автоматически:

In [15]:
np.arange(8).reshape(2, -1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Теперь порешаем задачки!

**Задание 1.** Реализуйте функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.

In [16]:
x = np.array([1, 5, 8, 6, 6, 1, 7, 4, 4, 0])
y = np.random.randint(9, size=10)

def max_element_before_zero(x):
    shift_by_one = np.hstack((1, x))
    bool_array = (shift_by_one == 0)[:np.size(shift_by_one) - 1]
    if np.size(x[bool_array]) == 0:
        return None
    else:
        return np.max(x[bool_array])
    
print ('Пример:', x, 'Максимальный элемент:', max_element_before_zero(x), sep='\n')
print ('Случайный вектор:', y, 'Максимальный элемент:', max_element_before_zero(y), sep='\n')

Пример:
[1 5 8 6 6 1 7 4 4 0]
Максимальный элемент:
None
Случайный вектор:
[5 7 0 2 5 8 4 8 4 2]
Максимальный элемент:
2


**Задание 2.** Реализуйте функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [17]:
def nearest_value(X, v):
    Y = np.abs(X - v)
    m = np.min(Y)
    inds = np.where(Y == m)
    return X[inds[0][0], inds[1][0]]

X = np.arange(0,10).reshape((2, 5))
v = 3.6
print ('Матрица:', X, 'Число:', v, 'Ближайший к числу элемент матрицы:', nearest_value(X, v), sep='\n')

Матрица:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Число:
3.6
Ближайший к числу элемент матрицы:
4


In [18]:
# Решение в одну строку
def get_nearest_value(X, v):
    return int(np.min(np.abs(X - v)) + v)

print ('Матрица:', X, 'Число:', v, 
       'Ближайший к числу элемент матрицы:', get_nearest_value(X, v), sep='\n')

Матрица:
[[0 1 2 3 4]
 [5 6 7 8 9]]
Число:
3.6
Ближайший к числу элемент матрицы:
4


**Задание 3.** Реализуйте функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на случайной матрице (для её генерации можно использовать, например, функцию [numpy.random.randint](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html)).

In [19]:
def scale(X):
    std_deviation = X.std(axis=0)
    std_deviation[std_deviation == 0] = 1
    X = X - X.mean(axis=0) # или X -= X.mean(axis=0) c преобразованием X = X.astype(np.float)
    X /= std_deviation
    return(X)

X = np.random.randint(-7, 8, size=(2,5))
print ('Матрица:', X, 'Масштабированная матрица:', scale(X), sep='\n')

Матрица:
[[ 4  2  0  0 -7]
 [ 7  0 -6 -6 -3]]
Масштабированная матрица:
[[-1.  1.  1.  1. -1.]
 [ 1. -1. -1. -1.  1.]]


##  2. Pandas и первичный анализ данных

**Pandas** (Python Data Analysis Library) — библиотека языка Python для удобных обработки и анализа данных.

Обычно первые шаги для EDA (Exploratory Data Analysis) выглядят примерно так:


<img src="https://www.researchgate.net/publication/329930775/figure/fig3/AS:873046667710469@1585161954284/The-fundamental-steps-of-the-exploratory-data-analysis-process.png" width=700>

Небольшой список литературы:

1. [Шпаргалка по pandas](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

2. [Введение в pandas](https://khashtamov.com/ru/pandas-introduction/)

3. [Статься в блоге сообщества OpenDataScience на Habr](https://habr.com/ru/company/ods/blog/322626/)

4. [Туториалы в официальной документации (на английском)](https://pandas.pydata.org/docs/getting_started/10min.html)

In [20]:
import pandas as pd

Качаем набор данных о футболистах из гитхаба курса, сохраняем в формате csv. Далее загружаем в Jupyter Notebook и внимательно указываем путь к файлу (в какие папки нужно перейти, чтобы увидеть файл).

In [21]:
df = pd.read_csv('data/data_football_profile.csv', sep='\t')

In [22]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Club', 'Value', 'Wage'], dtype='object')

Функция возвращает DataFrame (то есть таблицу), однако затем приобретает ещё много важных параметров, среди которых:

* sep — разделитель данных, по умолчанию ',';
* decimal — разделитель числа на целую и дробную часть, по умолчанию'.';
* names — список с названиями колонок, не обязательный параметр;
* skiprows — если файл содержит системную информацию, можно просто её пропустить. Необязательный параметр.

Дополнительные параметры можно посмотреть в [официальной документации.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

С помощью функции ```head``` можем посмотреть на первые несколько строк нашего датасета:

In [23]:
df.head()

Name   Age Nationality                 Club        Value      Wage
0      L. Messi  31.0   Argentina         FC Barcelona  110500000.0  565000.0
1           NaN  33.0    Portugal             Juventus   77000000.0  405000.0
2     Neymar Jr  26.0      Brazil  Paris Saint-Germain  118500000.0  290000.0
3        De Gea  27.0       Spain    Manchester United   72000000.0  260000.0
4  K. De Bruyne  27.0     Belgium      Manchester City  102000000.0  355000.0

Удалим колонку Value, к которой мы не знаем точную интерпретацию:

In [24]:
df.drop(['Value'], axis=1, inplace=True)

In [25]:
# последние несколько строк:
df.tail(3)

Name   Age Nationality              Club    Wage
12894             NaN  16.0     England  Cambridge United  1000.0
12895  D. Walker-Rice  17.0     England   Tranmere Rovers  1000.0
12896       G. Nugent  16.0     England   Tranmere Rovers  1000.0

Посмотрим на размер нашего датасета. Первое число – количество строк (наблюдений), второе – количество столбцов (признаков):

In [26]:
df.shape

(12897, 5)

Если вы хотите переименовать какую-то переменную, воспользуйтесь ```rename```:

In [27]:
df.rename({'Wage' : 'Salary'}, axis='columns', inplace=True)

In [28]:
df.columns

Index(['Name', 'Age', 'Nationality', 'Club', 'Salary'], dtype='object')

Давайте посмотрим на информацию о датасете. В .info() можно передать дополнительные параметры, среди которых:

* verbose: печатать ли информацию о DataFrame полностью (если таблица очень большая, то некоторая информация может потеряться);
* memory_usage: печатать ли потребление памяти (по умолчанию используется True, но можно поставить либо False, что уберёт потребление памяти, либо 'deep' , что подсчитает потребление памяти более точно);
* null_counts: подсчитывать ли количество пустых элементов (по умолчанию True).

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 5 columns):
Name           12266 non-null object
Age            12242 non-null float64
Nationality    12213 non-null object
Club           12226 non-null object
Salary         12263 non-null float64
dtypes: float64(2), object(3)
memory usage: 503.9+ KB


Можно вывести только тип данных в каждой колонке:

In [30]:
df.dtypes

Name            object
Age            float64
Nationality     object
Club            object
Salary         float64
dtype: object

Метод describe показывает основные статистические характеристики данных по каждому числовому признаку (типы int64 и float64): число непропущенных значений, среднее, стандартное отклонение, диапазон, медиану, 0.25 и 0.75 квартили.

In [31]:
df.describe()

Age         Salary
count  12242.000000   12263.000000
mean      24.814900    7530.946750
std        4.885492   23338.219396
min       16.000000    1000.000000
25%       21.000000    1000.000000
50%       24.000000    2000.000000
75%       28.000000    4000.000000
max       45.000000  565000.000000

Чтобы посмотреть статистику по нечисловым признакам (например, по строчным (object) или булевым (bool) данным), нужно явно указать интересующие нас типы в параметре метода describe include:

In [32]:
df.describe(include = ['object'])

Name Nationality             Club
count          12266       12213            12226
unique         11742         155              650
top     J. Rodríguez     England  Shonan Bellmare
freq               7        1297               30

Было бы полезно узнать, много ли у нас пропусков в датасете.

In [33]:
df.isna().sum()

Name           631
Age            655
Nationality    684
Club           671
Salary         634
dtype: int64

Чтобы удалить пропуски из данных, нужно вопспользоваться ```df.dropna()```, либо заполнить их значениями (например, средним) -  ```df.fillna(df['column_name'].mean())``` .
Если в датасете содержатся дубликаты строк - воспользуйтесь методом ```df.drop_duplicates()```.

In [34]:
# заполним количественные переменные средними значениями (медианой)
for column in df.columns:
    if df[column].dtype != 'object':
        df[column] = df[column].fillna(df[column].median())
        
# у оставшихся переменных удалим строки с пропусками
df.dropna(inplace=True)

df.isna().sum()

Name           0
Age            0
Nationality    0
Club           0
Salary         0
dtype: int64

Выведем уникальные значения по возрасту и сколько раз каждое из них встречается в датасете (по убыванию). 

In [35]:
df['Age'].value_counts()

24.0    1288
21.0     876
22.0     808
20.0     786
19.0     724
23.0     715
25.0     693
26.0     688
27.0     616
28.0     580
18.0     536
29.0     536
30.0     436
31.0     372
32.0     312
33.0     221
34.0     220
17.0     209
35.0     124
36.0     100
37.0      58
16.0      36
38.0      32
39.0      22
40.0      11
41.0       4
44.0       2
42.0       1
45.0       1
Name: Age, dtype: int64

Чтобы вывести уникальные значения в столбце или их количество, нужно использовать ```unique``` и ```nunique``` соответственно. Посмотрим, сколько у нас уникальных футбольных клубов. 

In [36]:
print('Всего {} футбольных клубов'.format(df['Club'].nunique()))

Всего 650 футбольных клубов


In [37]:
df['Club'].unique()[:10]

array(['FC Barcelona', 'Paris Saint-Germain', 'Manchester United',
       'Manchester City', 'Chelsea', 'Real Madrid', 'Atlético Madrid',
       'FC Bayern München', 'Juventus', 'Liverpool'], dtype=object)

Посмотрим на среднюю зарплату по клубу:

In [38]:
grouped = df.groupby('Club', as_index=False)['Salary'].mean()
# добавим сортировку по убыванию
grouped.sort_values(by='Salary', ascending=False)

Club         Salary
469       Real Madrid  187500.000000
212      FC Barcelona  184722.222222
325          Juventus  148461.538462
373   Manchester City  137761.904762
134           Chelsea  103894.736842
..                ...            ...
617    Viktoria Plzeň    1000.000000
90    Boyacá Chicó FC    1000.000000
317  Itagüí Leones FC    1000.000000
195       Dynamo Kyiv    1000.000000
416    Olympiacos CFP    1000.000000

[650 rows x 2 columns]

Добавим еще подсчет минимума, максимума и медианы по каждой группе:

In [39]:
df.groupby('Club')['Salary'].agg(['mean', 'min', 'max', 'median'])

mean     min      max  median
Club                                                       
 SSV Jahn Regensburg   3222.222222  1000.0   6000.0  3000.0
1. FC Heidenheim 1846  4000.000000  1000.0  14000.0  3000.0
1. FC Kaiserslautern   1454.545455  1000.0   3000.0  1000.0
1. FC Köln             9200.000000  1000.0  26000.0  4000.0
1. FC Magdeburg        3842.105263  1000.0   8000.0  4000.0
...                            ...     ...      ...     ...
Zagłębie Sosnowiec     1047.619048  1000.0   2000.0  1000.0
Çaykur Rizespor        5095.238095  1000.0  13000.0  4000.0
Örebro SK              1454.545455  1000.0   2000.0  1000.0
Östersunds FK          2055.555556  1000.0   8000.0  1000.0
Śląsk Wrocław          2045.454545  1000.0   4000.0  2000.0

[650 rows x 4 columns]

Сгруппируем одновременно по стране и клубу:

In [40]:
df.groupby(['Nationality', 'Club'], as_index=False)['Salary'].mean()

Nationality             Club   Salary
0     Afghanistan     Notts County   2000.0
1     Afghanistan        SV Meppen   1000.0
2     Afghanistan          Walsall   1000.0
3         Albania       AC Ajaccio   2000.0
4         Albania       Aalborg BK   1000.0
...           ...              ...      ...
3242     Zimbabwe   Club Brugge KV  20000.0
3243     Zimbabwe         Hobro IK   5000.0
3244     Zimbabwe      Le Havre AC   2000.0
3245     Zimbabwe  Orlando Pirates   1000.0
3246     Zimbabwe     Sparta Praha   1000.0

[3247 rows x 3 columns]

Добавим сортировку внутри групп:

In [41]:
df.groupby(['Nationality', 'Club']).apply(lambda x: x.sort_values(by='Salary', ascending=False))

Name   Age  Nationality  \
Nationality Club                                                      
Afghanistan Notts County    10007       N. Husin  21.0  Afghanistan   
            SV Meppen       7695         H. Amin  26.0  Afghanistan   
            Walsall         8395      M. Kouhyar  20.0  Afghanistan   
Albania     AC Ajaccio      4697         Q. Laçi  22.0      Albania   
            Aalborg BK      12510      B. Bytyqi  21.0      Albania   
...                                          ...   ...          ...   
Zimbabwe    Club Brugge KV  468       M. Nakamba  24.0     Zimbabwe   
            Hobro IK        2772      Q. Antipas  34.0     Zimbabwe   
            Le Havre AC     6090     T. Kadewere  22.0     Zimbabwe   
            Orlando Pirates 6502      M. Munetsi  24.0     Zimbabwe   
            Sparta Praha    1750   C. Nhamoinesu  32.0     Zimbabwe   

                                              Club   Salary  
Nationality Club                                             
Afghanistan Notts County    10007     Notts County   2000.0  
            SV Meppen       7695         SV Meppen   1000.0  
            Walsall         8395           Walsall   1000.0  
Albania     AC Ajaccio      4697        AC Ajaccio   2000.0  
            Aalborg BK      12510       Aalborg BK   1000.0  
...                                            ...      ...  
Zimbabwe    Club Brugge KV  468     Club Brugge KV  20000.0  
            Hobro IK        2772          Hobro IK   5000.0  
            Le Havre AC     6090       Le Havre AC   2000.0  
            Orlando Pirates 6502   Orlando Pirates   1000.0  
            Sparta Praha    1750      Sparta Praha   1000.0  

[11007 rows x 5 columns]

Теперь удалим лишние колонки. Обратите внимание на обратный слэш, это line continuation character.

In [42]:
df.groupby(['Nationality', 'Club']).apply(lambda x: x.sort_values(by='Salary', ascending=False)).\
                                                    drop(['Nationality', 'Club'], axis=1)

Name   Age   Salary
Nationality Club                                               
Afghanistan Notts County    10007       N. Husin  21.0   2000.0
            SV Meppen       7695         H. Amin  26.0   1000.0
            Walsall         8395      M. Kouhyar  20.0   1000.0
Albania     AC Ajaccio      4697         Q. Laçi  22.0   2000.0
            Aalborg BK      12510      B. Bytyqi  21.0   1000.0
...                                          ...   ...      ...
Zimbabwe    Club Brugge KV  468       M. Nakamba  24.0  20000.0
            Hobro IK        2772      Q. Antipas  34.0   5000.0
            Le Havre AC     6090     T. Kadewere  22.0   2000.0
            Orlando Pirates 6502      M. Munetsi  24.0   1000.0
            Sparta Praha    1750   C. Nhamoinesu  32.0   1000.0

[11007 rows x 3 columns]

Посчитаем арифметическое среднее, моду и медиану возраста футболистов (количественной переменной):

In [43]:
print('Среднее:', round(df['Age'].mean(), 2), 
      'Медиана:', df['Age'].median(), 
      'Мода:', df['Age'].mode()[0])

Среднее: 24.78 Медиана: 24.0 Мода: 24.0


Для качественных переменных с помощью pandas можно вывести моду. Посмотрим на самую часто встречающуюся национальность:

In [44]:
df['Nationality'].mode()

0    England
dtype: object

Часто возникает необходимость выбрать данные из DataFrame по определённому условию. Например, если в уже известном нам наборе данных о футболистах мы хотим выбрать только тех, у кого возраст больше 20 лет, используется следующий код:

In [45]:
df[df.Age > 20]

Name   Age Nationality                        Club    Salary
0           L. Messi  31.0   Argentina                FC Barcelona  565000.0
2          Neymar Jr  26.0      Brazil         Paris Saint-Germain  290000.0
3             De Gea  27.0       Spain           Manchester United  260000.0
4       K. De Bruyne  27.0     Belgium             Manchester City  355000.0
5          E. Hazard  27.0     Belgium                     Chelsea  340000.0
...              ...   ...         ...                         ...       ...
12838      D. Mackay  21.0    Scotland                  Kilmarnock    1000.0
12855      H. Norris  24.0     England             Oldham Athletic    1000.0
12861    Y. Uchimura  33.0       Japan  Hokkaido Consadole Sapporo    1000.0
12873  K. Pilkington  44.0     England            Cambridge United    1000.0
12889   M. Baldisimo  24.0      Canada      Vancouver Whitecaps FC    1000.0

[8716 rows x 5 columns]

**Задание:** Выберите футболистов, возраст которых больше среднего возраста футболистов, при условии, что они принадлежат ФК Барселона (Club == 'FC Barcelona').

In [46]:
df[(df.Age > df.Age.mean()) & (df.Club == 'FC Barcelona')]

Name   Age  Nationality          Club    Salary
0           L. Messi  31.0    Argentina  FC Barcelona  565000.0
7          L. Suárez  31.0      Uruguay  FC Barcelona  455000.0
18     M. ter Stegen  26.0      Germany  FC Barcelona  240000.0
20   Sergio Busquets  29.0        Spain  FC Barcelona  315000.0
32          Coutinho  26.0       Brazil  FC Barcelona  340000.0
49        Jordi Alba  29.0        Spain  FC Barcelona  250000.0
54             Piqué  31.0        Spain  FC Barcelona  240000.0
204     J. Cillessen  29.0  Netherlands  FC Barcelona  135000.0
605     T. Vermaelen  32.0      Belgium  FC Barcelona    2000.0

Чтобы объединить данные из нескольких датасетов по ключу (общей колонке), в pandas можно воспользовать встроенными аналогами SQL методов. В метод ```join``` в качестве аргумента how нужно указать тип объединения датасетов: inner, outer, left или right. 

In [47]:
# Вот так: 

In [48]:
df_info = pd.read_csv('data/data_football_info.csv', sep='\t')

joined_dfs = df_info.set_index('Name').join(df.set_index('Name'), how='inner').reset_index()
joined_dfs.head(5)

Name  Unnamed: 0 Position  Crossing  Finishing  HeadingAccuracy  \
0        A. Abang      8574.0       ST      30.0       61.0             67.0   
1   A. Abdellaoui     10604.0      NaN      56.0       25.0             56.0   
2         A. Abdi      2188.0       CM      68.0       61.0             59.0   
3   A. Abdu Jaber      7807.0       ST      39.0       66.0              NaN   
4  A. Abdulhameed     11820.0       GK      10.0        9.0             13.0   

   ShortPassing  Volleys  Dribbling  Curve  ...  SlidingTackle  GKDiving  \
0          52.0     58.0        NaN   30.0  ...           21.0       6.0   
1           NaN     32.0       39.0   30.0  ...           65.0      15.0   
2          74.0     64.0       70.0   68.0  ...           57.0       9.0   
3          49.0     64.0       61.0   59.0  ...           15.0       7.0   
4          26.0      6.0        6.0   11.0  ...           11.0      59.0   

   GKHandling  GKKicking  GKPositioning  GKReflexes   Age   Nationality  \
0         6.0        7.0           13.0         9.0  21.0      Cameroon   
1        10.0       14.0           13.0        14.0  25.0       Algeria   
2         6.0        8.0           11.0         8.0  31.0   Switzerland   
3        11.0        7.0            6.0        12.0  21.0       Eritrea   
4        57.0       51.0           52.0        58.0  24.0  Saudi Arabia   

                  Club   Salary  
0   New York Red Bulls   2000.0  
1              FC Sion   4000.0  
2  Sheffield Wednesday  13000.0  
3             Al Wehda   4000.0  
4             Al Hazem   1000.0  

[5 rows x 41 columns]