In [1]:
import numpy as np
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a = np.array([1,2,4])
b = np.array([3,4,5])
a + b

array([4, 6, 9])

In [2]:
np.mean(x) 

5.0

In [3]:
x.mean()

5.0

In [13]:
x = np.arange(10)
np.random.shuffle(x)
x

array([7, 9, 1, 3, 2, 0, 6, 5, 4, 8])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.sum(x == np.arange(10))

2

In [40]:
i = 5
j = 8
(x[i] == j)&(x[j] == i)

False

In [42]:
x[x[i]] == i

False

In [ ]:
x[np.arange()]

In [96]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
7*np.eye(5)

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

In [113]:
class Killer():
    # функция конструктор, вызывается 
    # каждый раз при создании новой игры 
    
    def __init__(self, n):
        # self - "обращиение к самому себе"
        self.n = n
        self.razdacha = None # раздачи нет, но будет
        self.reward = np.zeros(n)
        self.is_alive = np.ones(n)
        
    def first_step(self):
        x = np.arange(self.n)
        np.random.shuffle(x)
        self.razdacha = x
        
    def suicide_cnt(self):
        cnt = np.sum(self.razdacha == np.arange(self.n))
        return cnt
    
    # находится ли конкретный человек в мэтчинге
    def is_matching(self, i):
        return x[x[i]] == i
    
    def matching_cnt(self):
        y = self.razdacha[np.arange(self.n)] # номера жертв
        y = self.razdacha[y] # номера тех, кого хотят убить жертвы
        # совпадает ли жертва жертвы с убийцей
        cnt = np.sum(y == np.arange(self.n))
        return cnt - self.suicide_cnt()
    
    def game_step(self):
        candidates = np.arange(self.n)[self.is_alive == 1]
        u = np.random.choice(candidates)
        z = self.razdacha[u]
        self.is_alive[z] = 0
        self.reward[u] += 1
        # отдаём жертву убитого убийце
        self.razdacha[u] = self.razdacha[z]
        
        print(self.razdacha)
        print(self.is_alive)
        print(self.reward)
        print(' ')
        
    def play_game(self):
        while np.sum(self.is_alive) > 0:
            self.game_step()
        


In [114]:
game = Killer(10)
game.first_step()
print(game.razdacha)
print(' ')
game.play_game()

[2 1 3 9 0 8 6 4 5 7]
 
[2 1 3 9 2 8 6 4 5 7]
[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 
[2 1 3 9 2 8 6 4 8 7]
[0. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
[0. 0. 0. 0. 1. 0. 0. 0. 1. 0.]
 
[2 1 3 9 2 8 6 2 8 7]
[0. 1. 1. 1. 0. 0. 1. 1. 1. 1.]
[0. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 
[2 1 3 9 2 8 6 2 8 2]
[0. 1. 1. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 0. 1. 0. 0. 1. 1. 1.]
 
[2 1 3 2 2 8 6 2 8 2]
[0. 1. 1. 1. 0. 0. 1. 0. 1. 0.]
[0. 0. 0. 1. 1. 0. 0. 1. 1. 1.]
 
[2 1 3 2 2 8 6 2 8 2]
[0. 0. 1. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 1. 1. 0. 0. 1. 1. 1.]
 
[2 1 3 3 2 8 6 2 8 2]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 2. 1. 0. 0. 1. 1. 1.]
 
[2 1 3 3 2 8 6 2 8 2]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
[0. 1. 0. 3. 1. 0. 0. 1. 1. 1.]
 
[2 1 3 3 2 8 6 2 8 2]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 1. 0. 3. 1. 0. 1. 1. 1. 1.]
 
[2 1 3 3 2 8 6 2 8 2]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 3. 1. 0. 1. 1. 2. 1.]
 


In [95]:
game.matching_cnt()

4

In [93]:
game.razdacha

array([5, 1, 2, 8, 6, 3, 0, 4, 9, 7])

In [76]:
game.suicide_cnt()

2

In [ ]:
from tqdm import tqdm_notebook

In [87]:
n_obs = 10**5
x = np.zeros(n_obs)
y = np.zeros(n_obs)

for i in tqdm_notebook(range(n_obs)):
    game = Killer(100)
    game.first_step()
    x[i] = game.suicide_cnt()
    y[i] = game.matching_cnt()

100%|██████████| 100000/100000 [00:04<00:00, 23537.73it/s]


In [89]:
np.mean(x)

0.99531

In [90]:
np.mean(y)

1.00036