In [5]:
a = [1,2,3]
b = [4,5,6]
a + b

[1, 2, 3, 4, 5, 6]

In [6]:
import numpy as np 
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y

array([5, 7, 9])

In [3]:
x.mean() 

2.5

In [4]:
np.mean(x)

2.5

In [8]:
x.size

3

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
x = np.arange(10)
np.random.shuffle(x)
x

array([3, 1, 5, 9, 4, 2, 0, 7, 6, 8])

In [29]:
np.sum(x == np.arange(10))

3

In [37]:
i = 5
x[x[i]] == i

True

In [42]:
x

array([3, 1, 5, 9, 4, 2, 0, 7, 6, 8])

In [44]:
np.sum(x[x] == np.arange(10))

5

In [53]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [56]:
z = np.arange(5)
z[z < 3]

array([0, 1, 2])

In [94]:
class Killer():
    
    def __init__(self, n):
        self.n = n
        self.konvert = np.zeros(n) 
        self.is_alive = np.ones(n)
        self.reward = np.zeros(n) 
        self.chain = 0
        self.first_step()
        
    def __repr__(self): # что-то максимально компактное
        return f"Killer({self.n})" 
    
    def __str__(self): # более длинное человеческое описание
         return f"игра в киллера на({self.n}) человек"
        
    def first_step(self):
        self.konvert = np.arange(self.n)
        np.random.shuffle(self.konvert)
        
    def cnt_suicide(self):
        return np.sum(self.konvert == np.arange(self.n))
    
    def is_matching(self, i):
        return self.konvert[self.konvert[i]] == i

    def cnt_matching(self):
        cnt = np.sum(self.konvert[self.konvert] == np.arange(self.n))
        return cnt - self.cnt_suicide()
    
    #### Ход игры ####
    def step(self):
        murd = np.random.choice(np.arange(self.n)[self.is_alive > 0])
        dead = self.konvert[murd]
        
        self.is_alive[dead] = 0
        self.reward[murd] += 1
        self.konvert[murd] = self.konvert[dead]
        
#         print(self.konvert)
#         print(self.is_alive)
#         print(self.reward)
#         print(' ')
        
    def play_game(self):
        while np.sum(self.is_alive) > 0:
            
            # Неверно нашли, в коде ошибка
            ##################
            z = self.konvert == np.arange(self.n)
            if np.sum(z[self.is_alive > 0]) > 0:
                self.chain += 1
            ##################
            
            self.step()
            

    

In [95]:
k = Killer(10)
k

Killer(10)

In [96]:
print(k)

игра в киллера на(10) человек


In [50]:
from tqdm import tqdm # tqdm_notebook

n_obs = 10**5

X = np.zeros(n_obs)
Y = np.zeros(n_obs)
for i in tqdm(range(n_obs)):
    game = Killer(100)
    X[i] = game.cnt_suicide()
    Y[i] = game.cnt_matching()

100%|██████████| 100000/100000 [00:04<00:00, 21868.85it/s]


In [52]:
X

array([2., 1., 0., ..., 1., 1., 3.])

In [51]:
np.mean(X), np.mean(Y)

(0.99678, 0.997)

In [92]:
g = Killer(5)
g.konvert

array([0, 2, 1, 3, 4])

In [93]:
g.play_game()
g.chain

5